"""
=============================================================
 Lab 8 - Task 1: Schema Definition
 File: schema.py
=============================================================
Defines request and response models for FastAPI endpoints
=============================================================
"""

from pydantic import BaseModel, Field
from typing import Optional
from uuid import UUID


# ════════════════════════════════════════════════════════════
# REQUEST MODEL
# ════════════════════════════════════════════════════════════

class ChatRequest(BaseModel):
    """
    Input from client → FastAPI → LangGraph agent
    """
    message: str = Field(
        ...,
        description="User input message/query",
        min_length=1,
        example="Analyze my resume for a Data Scientist role"
    )

    thread_id: str = Field(
        ...,
        description="Unique conversation ID for maintaining memory",
        example="session_12345"
    )


# ════════════════════════════════════════════════════════════
# RESPONSE MODEL
# ════════════════════════════════════════════════════════════

class ChatResponse(BaseModel):
    """
    Output from agent → FastAPI → client
    """
    answer: str = Field(
        ...,
        description="Final response generated by the agent",
        example="Your resume shows strong Python and ML skills..."
    )

    status: str = Field(
        ...,
        description="Execution status of request",
        example="success"
    )

    thread_id: Optional[str] = Field(
        None,
        description="Echoed thread ID for tracking conversation"
    )